"""
Quiz generation endpoints — AI-powered quiz creation pipeline.

Provides 3 endpoints:
- POST /start: creates quiz artifact, returns artifact_id
- GET /{artifact_id}/stream: SSE endpoint for streaming question generation
- POST /match-curriculum: lightweight curriculum matching from free text
"""

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from supabase import Client

from app.api.deps import require_teacher
from app.api.http.schemas.quiz_generation import (
    CurriculumMatchIn,
    CurriculumMatchOut,
    CurriculumMatchNodeOut,
    CurriculumResolveIn,
    QuizGenerationStartIn,
    QuizGenerationStartOut,
)
from app.api.http.services.quiz_generation_service import (
    create_quiz_artifact,
    generate_questions_stream,
    match_curriculum,
    resolve_curriculum_codes,
)
from app.core.database import get_b2b_db

router = APIRouter()


@router.post("/start", response_model=QuizGenerationStartOut, status_code=201)
async def start_quiz_generation(
    payload: QuizGenerationStartIn,
    current_user: dict = Depends(require_teacher),
    db: Client = Depends(get_b2b_db),
):
    """Create a quiz artifact and return its ID for streaming generation."""
    artifact = create_quiz_artifact(
        db,
        current_user["organization_id"],
        current_user["id"],
        payload,
    )
    return QuizGenerationStartOut(
        artifact_id=artifact["id"],
        artifact_name=artifact["artifact_name"],
    )


@router.get("/{artifact_id}/stream")
async def stream_quiz_generation(
    artifact_id: str,
    current_user: dict = Depends(require_teacher),
    db: Client = Depends(get_b2b_db),
):
    """
    SSE endpoint that generates quiz questions and streams them in real time.

    Each question is inserted into the DB and yielded as an SSE event
    as soon as it is generated by the LLM.
    """
    generator = generate_questions_stream(
        db,
        artifact_id,
        current_user["organization_id"],
        current_user["id"],
    )
    return StreamingResponse(
        generator,
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


@router.post("/match-curriculum", response_model=CurriculumMatchOut)
async def match_curriculum_endpoint(
    payload: CurriculumMatchIn,
    current_user: dict = Depends(require_teacher),
    db: Client = Depends(get_b2b_db),
):
    """
    Match a teacher's free-text description to curriculum codes.

    Returns a list of matched curriculum nodes for the teacher to confirm.
    """
    matched_nodes = await match_curriculum(db, payload)
    return CurriculumMatchOut(matched_nodes=matched_nodes)


@router.post("/resolve-codes", response_model=list[CurriculumMatchNodeOut])
async def resolve_codes_endpoint(
    payload: CurriculumResolveIn,
    current_user: dict = Depends(require_teacher),
    db: Client = Depends(get_b2b_db),
):
    """Resolve curriculum codes to full node objects (id, code, title, etc.)."""
    return resolve_curriculum_codes(
        db,
        payload.subject_id,
        payload.year_level,
        payload.codes,
    )
