/**
 * Post-processing: replace card/container borders with Rough.js hand-drawn
 * rectangles ONLY inside .sl-visual containers (generated by the visual service).
 *
 * Elements outside .sl-visual (executor-generated) are NOT touched.
 */

const ROUGH_CDN = "/roughjs/rough.js";

interface RoughifyConfig {
    selector: string;
    roughness: number;
    strokeWidth: number;
    stroke: string;
    fill: string;
    fillStyle: "solid" | "hachure" | "cross-hatch" | "zigzag";
    radius: number;
}

// Only target elements INSIDE .sl-visual containers
const ROUGHIFY_TARGETS: RoughifyConfig[] = [
    {
        selector: ".sl-visual .sl-info-card",
        roughness: 0.7,
        strokeWidth: 1.5,
        stroke: "var(--sl-color-accent)",
        fill: "var(--sl-color-accent-soft)",
        fillStyle: "solid",
        radius: 14,
    },
    {
        selector: ".sl-visual .sl-container-accent",
        roughness: 0.6,
        strokeWidth: 1.5,
        stroke: "var(--sl-color-accent)",
        fill: "var(--sl-color-accent-soft)",
        fillStyle: "solid",
        radius: 14,
    },
    {
        selector: ".sl-visual .sl-container",
        roughness: 0.5,
        strokeWidth: 1.2,
        stroke: "rgba(21,49,107,0.15)",
        fill: "#ffffff",
        fillStyle: "solid",
        radius: 14,
    },
    {
        // The controls panel background
        selector: ".sl-visual .sl-controls",
        roughness: 0.4,
        strokeWidth: 1,
        stroke: "rgba(21,49,107,0.1)",
        fill: "#f8f7f4",
        fillStyle: "solid",
        radius: 12,
    },
];

function resolveColor(el: HTMLElement, value: string): string {
    if (!value.startsWith("var(")) return value;
    const varName = value.slice(4, -1).trim();
    return getComputedStyle(el).getPropertyValue(varName).trim() || value;
}

function roundedRectPath(x: number, y: number, w: number, h: number, r: number): string {
    return `M ${x + r} ${y} L ${x + w - r} ${y} Q ${x + w} ${y} ${x + w} ${y + r} L ${x + w} ${y + h - r} Q ${x + w} ${y + h} ${x + w - r} ${y + h} L ${x + r} ${y + h} Q ${x} ${y + h} ${x} ${y + h - r} L ${x} ${y + r} Q ${x} ${y} ${x + r} ${y} Z`;
}

async function ensureRoughLoaded(): Promise<any> {
    if ((window as any).rough) return (window as any).rough;

    return new Promise((resolve, reject) => {
        const existing = document.querySelector(`script[src="${ROUGH_CDN}"]`);
        if (existing) {
            if ((window as any).rough) return resolve((window as any).rough);
            existing.addEventListener("load", () => resolve((window as any).rough));
            return;
        }

        const script = document.createElement("script");
        script.src = ROUGH_CDN;
        script.onload = () => resolve((window as any).rough);
        script.onerror = reject;
        document.head.appendChild(script);
    });
}

function roughifyElement(el: HTMLElement, rough: any, config: RoughifyConfig) {
    if (el.querySelector(".roughify-overlay")) return;

    const w = el.offsetWidth;
    const h = el.offsetHeight;
    if (w < 10 || h < 10) return;

    // Create SVG overlay
    const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg.setAttribute("width", String(w));
    svg.setAttribute("height", String(h));
    svg.setAttribute("viewBox", `0 0 ${w} ${h}`);
    svg.classList.add("roughify-overlay");
    Object.assign(svg.style, {
        position: "absolute",
        top: "0",
        left: "0",
        width: "100%",
        height: "100%",
        pointerEvents: "none",
        zIndex: "0",
    });

    const rc = rough.svg(svg);

    const resolvedStroke = resolveColor(el, config.stroke);
    const resolvedFill = resolveColor(el, config.fill);

    // Draw rounded rough rectangle using path
    const p = 1;
    const path = roundedRectPath(p, p, w - p * 2, h - p * 2, config.radius);
    const node = rc.path(path, {
        roughness: config.roughness,
        strokeWidth: config.strokeWidth,
        stroke: resolvedStroke,
        fill: resolvedFill,
        fillStyle: config.fillStyle,
        bowing: 1,
    });
    svg.appendChild(node);

    // Position element for overlay
    el.style.position = "relative";
    el.style.background = "transparent";
    el.style.border = "none";
    el.style.borderRadius = "0";
    el.style.boxShadow = "none";

    // Ensure content is above the SVG
    Array.from(el.children).forEach((child) => {
        if (child !== svg && child instanceof HTMLElement) {
            child.style.position = "relative";
            child.style.zIndex = "1";
        }
    });

    el.insertBefore(svg, el.firstChild);
}

/**
 * Roughify cards/containers ONLY inside .sl-visual elements.
 * Executor-generated elements outside .sl-visual are untouched.
 */
export async function roughifyCards(canvas: HTMLElement): Promise<void> {
    try {
        const rough = await ensureRoughLoaded();
        if (!rough) return;

        for (const target of ROUGHIFY_TARGETS) {
            const elements = canvas.querySelectorAll<HTMLElement>(target.selector);
            elements.forEach((el) => roughifyElement(el, rough, target));
        }
    } catch (err) {
        console.warn("roughifyCards failed:", err);
    }
}
