/**
 * Dynamic Lucide icon resolver
 * Maps string icon names from the DB to Lucide React components.
 */
import {
    BookOpen,
    Calculator,
    Leaf,
    Globe,
    Palette,
    Activity,
    Users,
    Heart,
    Map,
    Microscope,
    Eye,
    Cpu,
    Music,
    Laptop,
    Flag,
    Hourglass,
    Atom,
    Lightbulb,
    Pencil,
    TrendingUp,
    Beaker,
    Mountain,
    Code,
    Brain,
    Fingerprint,
    Scale,
    Mic,
    Video,
    Wrench,
    Clapperboard,
    BookOpenCheck,
    Zap,
    type LucideIcon,
    FileText,
    FolderOpen,
    Dna,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
    book: BookOpen,
    "book-open": BookOpenCheck,
    calculator: Calculator,
    leaf: Leaf,
    globe: Globe,
    palette: Palette,
    run: Activity,
    users: Users,
    heart: Heart,
    map: Map,
    microscope: Microscope,
    eye: Eye,
    cpu: Cpu,
    music: Music,
    laptop: Laptop,
    flag: Flag,
    hourglass: Hourglass,
    atom: Atom,
    lightbulb: Lightbulb,
    pencil: Pencil,
    "trending-up": TrendingUp,
    beaker: Beaker,
    mountain: Mountain,
    code: Code,
    brain: Brain,
    fingerprint: Fingerprint,
    scale: Scale,
    mic: Mic,
    video: Video,
    tool: Wrench,
    clapperboard: Clapperboard,
    brush: Palette,
    "feather": Pencil,
    museum: BookOpenCheck,
    cube: Cpu,
    zap: Zap,
    dna: Dna,
};

export function getSubjectIcon(iconName: string | null | undefined): LucideIcon {
    if (!iconName) return FileText;
    return ICON_MAP[iconName] ?? FolderOpen;
}
